### ISSUE TITLE
Duplicate values for FIPS code 29189

### ISSUE THREAD

**Issue by benjaminEwhite** [descarteslabs/DL-COVID-19#3]
I expected that there would only be a single entry for each FIPS + date combination. 

However, I find that for FIPS code 29189, there are two entries, which differ in terms of values for `admin2` and the values for samples, m50 etc. Specifically, there's one set of entries for City of Saint Louis, and another for Saint Louis County. 

Is my expectation incorrect?

**Comment by mikewarren0** [comment]
Your expectation is correct.  The FIPS code for City of Saint Louis should be 29510.  We will fix this immediately.
